project_id = "vcevdkggfbhftaegkkkk"

[functions.generate_notes]
verify_jwt = false

[functions.generate_derivatives]
verify_jwt = false

[functions.generate_podcast]
verify_jwt = false

[functions.chat]
verify_jwt = false