// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const CONFIGURED_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const CONFIGURED_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// Placeholders keep the module importable in test/build environments that have
// no credentials. Any real request against them will fail, so make the cause loud.
if (!CONFIGURED_URL || !CONFIGURED_KEY) {
  console.error(
    "[supabase] NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_ANON_KEY are not set. " +
      "Copy .env.example to .env.local and fill them in — every request will fail until you do.",
  );
}

export const SUPABASE_URL = CONFIGURED_URL || "https://placeholder-project.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = CONFIGURED_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYWNlaG9sZGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE1OTg4NzQ5OTIsImV4cCI6MTkxNDQzNDk5Mn0.placeholder";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});